### ISSUE TITLE
Introducing a constant for the "default" tube name

### ISSUE THREAD

**Issue by svisser** [earl/beanstalkc#72]
By default, a `beanstalkc.Connection()` instance listens to the `"default"` tube as specified by the beanstalkd protocol (https://github.com/kr/beanstalkd/blob/master/doc/protocol.txt).

It would be useful if there was a constant `DEFAULT_TUBE_NAME` for that in this library (similar to other defaults) as some application code may wish to use it (e.g., for the purpose of watching other tubes and ignoring that particular default tube).

If this idea seems sensible (even though the rest of `beanstalkc.py` may not use that constant), I'm happy to create a pull request.

**Comment by earl** [comment]
Good idea, I'll be happy to merge it!

**Comment by earl** [comment]
Merged via PR #73.
